### ISSUE TITLE
httpUploadProgress hook?

### ISSUE THREAD

**Issue by danpaz** [chrispasakarnis/http-to-s3#1]
This lib is really useful, thanks :)

Is there a way to hook into the `httpUploadProgress` event? http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#httpUploadProgress-event

Example usage from https://aws.amazon.com/blogs/developer/announcing-the-amazon-s3-managed-uploader-in-the-aws-sdk-for-javascript/:
```
s3obj.upload({Body: body}).
  on('httpUploadProgress', function(evt) {
    console.log('Progress:', evt.loaded, '/', evt.total); 
  }).
  send(function(err, data) { console.log(err, data) });
```

Maybe add an option to pass in a listener `options.s3.httpUploadProgress`?

**Comment by chrispasakarnis** [comment]
Thanks for the suggestion. I've pushed a change and published to NPM that includes the ability to attach a listener to the options payload on a request.

**Comment by danpaz** [comment]
Thanks! 😄
