### ISSUE TITLE
Does Not install from npm command.

### ISSUE THREAD

**Issue by dcdushan** [chrispasakarnis/http-to-s3#3]
Command used : **npm install --save http-to-s3**
libs and .js files seems to be missing under node_modules/http-to-s3.
<img width="264" alt="screen shot 2018-05-03 at 8 18 01 am" src="https://user-images.githubusercontent.com/6904476/39558247-967095a8-4eaa-11e8-8018-1a7a55f0d637.png">

**Comment by chrispasakarnis** [comment]
Ah, whoops. This has been resolved and a new version has been published to NPM. Thanks for the issue.
